[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Configurações de produção
[context.production]
  environment = { NODE_ENV = "production" }

# Configurações de preview para branches
[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Configurações para deploy de pull requests
[context.deploy-preview]
  environment = { NODE_ENV = "development" }

# Redirecionamentos e rewrite rules para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200